// frontend-react/src/pages/Home.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import Cashbag from '../images/cashbag.png';
import Logo from '../images/logo.png';
import '../styles/Home.css';

const Home = () => {
    return (
        <div>
            <div className="scrollable-content">
                <div className="text-container">
                    <h1>Welcome to ExchangExpress</h1>
                    <h2>The fastest place to exchange currencies</h2>
                </div>
                <img src={Cashbag} alt="Moneybag" />
            </div>

            <header>
                <Link to={"/"}>
                    <div className="logo-container">
                        <img src={Logo} alt="Logo" height="50" width="50" />
                        <span>ExchangExpress</span>
                    </div>
                </Link>

                <div className="RNLButton">
                    <button className="Newsbutton"><Link to={"/News"}>News</Link></button>
                    <button className="Registerbutton"><Link to={"/register"}>Signup</Link></button>
                    <button className="Loginbutton"><Link to={"/login"}>Login</Link></button>
                </div>
            </header>
        </div>
    );
}

export default Home;

// frontend-angular/src/app/home/home.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { LoginComponent } from '../login/login.component';
import { SignupComponent } from '../signup/signup.component';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [RouterOutlet, SignupComponent, LoginComponent],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent {

}


<html lang="en">
<head>
    <title>Home Page</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <div class="scrollable-content">
        <h1>Welcome to ExchangExpress</h1>
        <img src="images/cashbag.png" alt="Moneybag">
    </div>

    <header>
        <a href="home.component.html" class="logo">
            <div class="logo-container">
                <img src="images/logo.png" alt="Logo" height="50" width="75">
                <span>ExchangExpress</span>
            </div>
        </a>
        <nav>
            <!-- <a class="button" routerLink="/signup" routerLinkActive="activebutton" ariaCurrentWhenActive="page">Sign Up</a>
            <a class="button" routerLink="/login" routerLinkActive="activebutton" ariaCurrentWhenActive="page">Login</a> -->
            <button routerLink="/signup">Sign Up</button>
            <button routerLink="/login">Login</button>
        </nav>
    </header>
</body>

</html>
